### ISSUE TITLE
How to Build ?

### ISSUE THREAD

**Issue by Mr-Basirnia** [JetBrains/colorSchemeTool#41]
I used python 3.10 but I cant convert theme

when run convert.sh get error

```
converting ./vscThemes/Monokai.json to ./tmThemes/Monokai.tmTheme ...
converting ./vscThemes/dark_plus.json to ./tmThemes/dark_plus.tmTheme ...
C:\Users\Mr-Basirnia\Documents\Github\colorSchemeTool\vscToTm.js:43
        if (fromKey in this.vscThemeColors) {
                    ^

TypeError: Cannot use 'in' operator to search for 'editorCursor.foreground' in undefined
    at SettingsMapper.addSetting (C:\Users\Mr-Basirnia\Documents\Github\colorSchemeTool\vscToTm.js:43:21)
    at convert (C:\Users\Mr-Basirnia\Documents\Github\colorSchemeTool\vscToTm.js:21:12)
    at Object.<anonymous> (C:\Users\Mr-Basirnia\Documents\Github\colorSchemeTool\vscToTm.js:50:47)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:18:47

Node.js v18.9.0
converting ./tmThemes/Active4D.tmTheme to ./intellijThemes/Active4D.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/All Hallow's Eve.tmTheme to ./intellijThemes/All Hallow's Eve.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/Amy.tmTheme to ./intellijThemes/Amy.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/Blackboard.tmTheme to ./intellijThemes/Blackboard.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/Cobalt.tmTheme to ./intellijThemes/Cobalt.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/Dawn.tmTheme to ./intellijThemes/Dawn.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/Eiffel.tmTheme to ./intellijThemes/Eiffel.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/Espresso Libre.tmTheme to ./intellijThemes/Espresso Libre.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/Github.tmTheme to ./intellijThemes/Github.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/IDLE.tmTheme to ./intellijThemes/IDLE.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/LAZY.tmTheme to ./intellijThemes/LAZY.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/Mac Classic.tmTheme to ./intellijThemes/Mac Classic.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/MagicWB (Amiga).tmTheme to ./intellijThemes/MagicWB (Amiga).icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/Monokai Bright.tmTheme to ./intellijThemes/Monokai Bright.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/Monokai.tmTheme to ./intellijThemes/Monokai.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/Pastels on Dark.tmTheme to ./intellijThemes/Pastels on Dark.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/Railscasts.tmTheme to ./intellijThemes/Railscasts.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/Slush & Poppies.tmTheme to ./intellijThemes/Slush & Poppies.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/Solarized (Dark).tmTheme to ./intellijThemes/Solarized (Dark).icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/Solarized (Light).tmTheme to ./intellijThemes/Solarized (Light).icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/SpaceCadet.tmTheme to ./intellijThemes/SpaceCadet.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/Sunburst.tmTheme to ./intellijThemes/Sunburst.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/Twilight.tmTheme to ./intellijThemes/Twilight.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/Zenburnesque.tmTheme to ./intellijThemes/Zenburnesque.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
converting ./tmThemes/iPlastic.tmTheme to ./intellijThemes/iPlastic.icls ...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
```

**Comment by sebastian-nunez** [comment]
I haven't used it, but this is the spec:
> "Note that the tool requires **Python version 2.7.** The default version of Python installed on macOS X Snow Leopard is 2.6; you'll need to use Python from MacPorts/Homebrew if you'd  like to run the tool on 10.6."
